name: Unit test
on:
  pull_request:

jobs:
  build_opam:
    name: Builds the project and performs the unit tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 5.0.0
    runs-on: ${{ matrix.os }}

    steps:
      - name: configure git LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout code
        uses: actions/checkout@v2
        #
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test
      - run: opam install . --deps-only --with-test -y
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
